package com.example.employeemanagement.mapper;

import com.example.employeemanagement.dto.EmployeeRequest;
import com.example.employeemanagement.dto.EmployeeResponse;
import com.example.employeemanagement.entity.Employee;
import org.springframework.stereotype.Component;

/*
 * @Component:
 * What    → Marks this class as a Spring-managed bean.
 * Why     → Allows Spring to inject it into EmployeeServiceImpl via constructor injection.
 *            Without this, Spring wouldn't know this class exists.
 * Internal → During component scanning, Spring creates a singleton instance of
 *             EmployeeMapper and registers it in the ApplicationContext.
 * Where   → Use @Component for generic Spring beans that don't fit
 *            @Service, @Repository, or @Controller categories.
 *            A mapper is a utility/helper — @Component is the right choice.
 */
@Component
public class EmployeeMapper {

    /*
     * toEntity: converts EmployeeRequest → Employee
     *
     * Called in the service layer when creating a new employee.
     * Notice what we do NOT map:
     *   - id        → not set because the DB generates it (AUTO_INCREMENT)
     *   - createdAt → not set because @CreationTimestamp handles it
     *   - updatedAt → not set because @UpdateTimestamp handles it
     *
     * We use the @Builder pattern (generated by Lombok) for clean, readable construction.
     * The alternative would be:
     *   Employee e = new Employee();
     *   e.setFirstName(request.getFirstName());
     *   ... 8 more setters
     * Builder is more readable and less error-prone.
     */
    public Employee toEntity(EmployeeRequest request) {
        return Employee.builder()
                .firstName(request.getFirstName())
                .lastName(request.getLastName())
                .email(request.getEmail())
                .phoneNumber(request.getPhoneNumber())
                .department(request.getDepartment())
                .jobTitle(request.getJobTitle())
                .salary(request.getSalary())
                .hireDate(request.getHireDate())
                .build();
    }

    /*
     * toResponse: converts Employee → EmployeeResponse
     *
     * Called in the service layer before returning data to the controller.
     * Here we DO map id, createdAt, and updatedAt because the client
     * needs the id for follow-up requests and the timestamps for audit purposes.
     *
     * This is where you control exactly what the API exposes.
     * If you add a sensitive field to Employee (e.g., internalNotes),
     * it won't appear in the API response unless you explicitly add it here.
     */
    public EmployeeResponse toResponse(Employee employee) {
        return EmployeeResponse.builder()
                .id(employee.getId())
                .firstName(employee.getFirstName())
                .lastName(employee.getLastName())
                .email(employee.getEmail())
                .phoneNumber(employee.getPhoneNumber())
                .department(employee.getDepartment())
                .jobTitle(employee.getJobTitle())
                .salary(employee.getSalary())
                .hireDate(employee.getHireDate())
                .createdAt(employee.getCreatedAt())
                .updatedAt(employee.getUpdatedAt())
                .build();
    }

    /*
     * updateEntityFromRequest: applies EmployeeRequest fields onto an existing Employee
     *
     * Called in the service layer when updating an employee.
     * WHY NOT just use toEntity() for updates?
     *
     * toEntity() creates a brand new Employee object with no id.
     * If you save that, Hibernate treats it as a new INSERT, not an UPDATE.
     * You'd lose the original createdAt timestamp too.
     *
     * Instead, we load the existing Employee from the DB (preserving id and createdAt),
     * then overwrite only the fields the client is allowed to change.
     * Hibernate detects the changes and issues an UPDATE statement.
     */
    public void updateEntityFromRequest(EmployeeRequest request, Employee employee) {
        employee.setFirstName(request.getFirstName());
        employee.setLastName(request.getLastName());
        employee.setEmail(request.getEmail());
        employee.setPhoneNumber(request.getPhoneNumber());
        employee.setDepartment(request.getDepartment());
        employee.setJobTitle(request.getJobTitle());
        employee.setSalary(request.getSalary());
        employee.setHireDate(request.getHireDate());
        // id, createdAt, updatedAt are intentionally NOT updated here
    }
}
